version: '3.8'

services:
  db:
    image: ethan9rohman3/honors_ui:db
    restart: always
    environment:
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: 1057
      POSTGRES_DB: ui_study
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: ethan9rohman3/honors_ui:nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/collected_static   # Mount the collected_static directory
    ports:
      - "8080:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:   # Define the static_volume volume

